[package]
name = "synth_wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
rustysynth = "1.2.0"
hound = "3.4.0"
wasm-bindgen = "0.2.81"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
